# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    .Call(`_ale_hello_world`)
}

new_ale <- function() {
    .Call(`_ale_new_ale`)
}

ale_set_bool <- function(self, name, value) {
    invisible(.Call(`_ale_ale_set_bool`, self, name, value))
}

ale_set_float <- function(self, name, value) {
    invisible(.Call(`_ale_ale_set_float`, self, name, value))
}

ale_set_int <- function(self, name, value) {
    invisible(.Call(`_ale_ale_set_int`, self, name, value))
}

ale_load_rom <- function(self, rom) {
    invisible(.Call(`_ale_ale_load_rom`, self, rom))
}

ale_reset_game <- function(self) {
    invisible(.Call(`_ale_ale_reset_game`, self))
}

ale_random_action <- function(self) {
    .Call(`_ale_ale_random_action`, self)
}

ale_get_screen_rgb <- function(self) {
    .Call(`_ale_ale_get_screen_rgb`, self)
}

ale_get_screen_grayscale <- function(self) {
    .Call(`_ale_ale_get_screen_grayscale`, self)
}

